---
certificates_directory: /mnt/vault/certs
default_2fa_method: "totp"
default_redirection_url: https://auth.andronics.io
theme: dark

authentication_backend:
  file:
    path: /var/lib/authelia/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
    watch: true

log:
  level: info
  file_path: /var/log/authelia/authelia.log

notifier:
  disable_startup_check: false
  smtp:
    username: scox@play.schule
    sender: Authelia <admin@andronics.io>
    host: smtp.gmail.com
    port: 587
    
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

session:
  name: authelia_session
  domain: andronics.io
  expiration: 86400 # 24 hours
  inactivity: 3600 # 1 minutes
  remember_me_duration: 1M
  same_site: lax

server:
  host: 0.0.0.0
  port: 9091

storage:
  local:
    path: /var/lib/authelia/storage.sqlite3

totp:
  issuer: authelia.com

...